
[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[env]
TERM = "xterm-256color"

# -------------------------------------------
# Fonts
# -------------------------------------------

[font]
size = 14.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

# -------------------------------------------
# Window
# -------------------------------------------

[window]
dynamic_padding = true
resize_increments = true
decorations = "full"

[general]
import = ["~/.config/alacritty/themes/catppuccin-macchiato.toml"]
