source=~/.config/hypr/themes/catppuccin-mocha.conf

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.config/wallpapers/mountains.png
}

input-field {
    monitor =

    font_color = $text                      
    inner_color = $crust                    
    outer_color = $mauve
    font_family = "CaskaydiaCove Nerd Font"

    position = 0, 0
    halign = center
    valign = center
    size = 450, 75
    outline_thickness = 4
    rounding = -1
    
    placeholder_text =
    check_color = $yellow
    fail_color = $red
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    shadow_passes = 0
    fade_on_empty = true
}
